apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: my-container1
          image: piyushacet/abc_image:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "30001"
              # valueFrom:
              #   configMapKeyRef:
              #     name: my-config
              #     key: PORT1
          ports:
            - containerPort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: my-app1
  ports:
    - name: http
      port: 80
      targetPort: 30001
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress1
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - piyush1.nxtcoder17.me
      secretName: piyush1.nxtcoder17.me-tls
  rules:
    - host: piyush1.nxtcoder17.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service1
                port:
                  name: http
